import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the initial state for the counter feature
interface CounterState {
  value: number;
}

const initialState: CounterState = {
  value: 0,
};

// Create a slice for the counter feature using createSlice from redux toolkit
const counterSlice = createSlice({
  name: "counter", // A unique name for the slice
  initialState, // The initial state for the slice
  reducers: {
    // An object of reducer functions that modify the state based on actions
    increment(state) {
      // Redux toolkit allows us to mutate the state directly using Immer library under the hood
      state.value += 1;
    },
    decrement(state) {
      state.value -= 1;
    },
    incrementByAmount(state, action: PayloadAction<number>) {
      // We can also access the action payload in the reducer function
      state.value += action.payload;
    },
  },
});

// Export the actions generated by createSlice for this slice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Export the reducer function as default export for this slice
export default counterSlice.reducer;
